### ISSUE TITLE
Cannot set property 'outlineProperties' of null

### ISSUE THREAD

**Issue by huntinghawk1415** [exceljs/exceljs#655]
I'm attempting to read an xlsx file that's been generated from company software. I'm able to read and write all other files other than those generated xlsx files, so I'm not 100% sure whats going on in the back end to cause this. Regardless, here's my error:

```
PS C:\Users\ME\Desktop\excel test> node app.js
TypeError: Cannot set property 'outlineProperties' of null 
     at module.exports.parseClose (C:\Users\ME\Desktop\excel test\node_modules\exceljs\dist\es5\xlsx\xform\sheet\worksheet-xform.js:232:40)
     at SAXStream.<anonymous> (C:\Users\JacobL\Desktop\excel test\node_modules\exceljs\dist\es5\xlsx\xform\base-xform.js:83:21)
     at emitOne (events.js:116:13)
     at SAXStream.emit (events.js:211:7)
     at SAXParser.me._parser.(anonymous function) [as onclosetag] (C:\Users\ME\Desktop\excel test\node_modules\sax\lib\sax.js:258:17)
     at emit (C:\Users\ME\Desktop\excel test\node_modules\sax\lib\sax.js:624:35)
     at emitNode (C:\Users\ME\Desktop\excel test\node_modules\sax\lib\sax.js:629:5)
     at closeTag (C:\Users\ME\Desktop\excel test\node_modules\sax\lib\sax.js:889:7)
     at SAXParser.write (C:\Users\ME\Desktop\excel test\node_modules\sax\lib\sax.js:1436:13)
     at SAXStream.write (C:\Users\ME\Desktop\excel test\node_modules\sax\lib\sax.js:239:18)
```

and my code:

```
const transformInputData = () => new Promise((res, rej) => {
     let workbook = new Excel.Workbook()
     const path1 = 'C:\\Users\\ME\\Desktop\\Complete Reports\\FILENAME.xlsx'

     workbook.xlsx.readFile(path1).then(() => {
       res('good')
     }).catch(err => console.log(err))
})
```

**Comment by halfer** [comment]
Also asked [on Stack Overflow](https://stackoverflow.com/questions/52594745/cannot-set-property-outlineproperties-of-null-exceljs).

**Comment by huntinghawk1415** [comment]
> Also asked [on Stack Overflow](https://stackoverflow.com/questions/52594745/cannot-set-property-outlineproperties-of-null-exceljs).

Not sure if you're alerting me or anyone else who happens by this issue. Regardless, I'm the one who posted the question on Stack Overflow assuming it might have a quicker response rate than here (to no avail, sadly).

**Comment by SreekanthMekala** [comment]
Is this issue is solved? Can you please update the status

**Comment by huntinghawk1415** [comment]
This appears to have been fixed as of my last test with 3.8.0

**Comment by tpkn** [comment]
It's still a problem for me:

    TypeError: Cannot set property 'outlineProperties' of null
        at WorkSheetXform.parseClose (E:\test\parser\node_modules\exceljs\lib\xlsx\xform\sheet\worksheet-xform.js:388:40)
        at saxStream.sax.on.node (E:\test\parser\node_modules\exceljs\lib\xlsx\xform\base-xform.js:91:21)
        at SaxesParser.closeTag (E:\test\parser\node_modules\saxes\saxes.js:2012:65)
        at SaxesParser.sCloseTag (E:\test\parser\node_modules\saxes\saxes.js:1601:18)
        at SaxesParser.write (E:\test\parser\node_modules\saxes\saxes.js:483:36)
        at SAXStream._write (E:\test\parser\node_modules\exceljs\lib\utils\sax-stream.js:11:14)
        at doWrite (_stream_writable.js:415:12)
        at writeOrBuffer (_stream_writable.js:399:5)
        at SAXStream.Writable.write (_stream_writable.js:299:11)
        at resolve (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:205:14)
        at new Promise (<anonymous>)
        at write (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:204:14)
        at Array.map (<anonymous>)
        at StreamBuf._pipe (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:210:34)
        at StreamBuf._flush (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:275:14)
        at writeComplete (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:288:14)


v3.8.2
