### ISSUE TITLE
Lib contains class syntax, not compatible with IE11

### ISSUE THREAD

**Issue by yoyo837** [exceljs/exceljs#989]
https://unpkg.com/exceljs@3.2.0/dist/exceljs.js

line 17612:

![image](https://user-images.githubusercontent.com/6134547/67266184-24e0a880-f4e2-11e9-9c86-abb94abf72e5.png)

**Comment by thewarpaint** [comment]
I think you would have to use the ES5 files instead, e.g. https://unpkg.com/exceljs@3.2.0/dist/es5/csv/csv.js

**Comment by szymanek-event-it** [comment]
Importing the es5 version doesn't fix the issue for me using webpack.

I'm importing the lib like this
import ExcelJS from 'exceljs/dist/es5/exceljs.browser.js'

The webpack created chunk-vendors includes class definitions thereby breaking the bundled code in Internet Explorer 11. Modern browsers work fine. I have identified exceljs to be the source of the problem. This started happening from version 3, and the switch to modern JS as the default.

I've tried deleting everything from the module except the es5 files. I've tried resetting values in the package.json to how they were in version 2. Nothing helped.

I'm out of ideas.

**Comment by guyonroche** [comment]
Fixed in v3.3.0

**Comment by guyonroche** [comment]
Added a monkey-patch that adds a browserify property to the fast-csv package.json before the build. Longer term will try to have it PR'd into the package properly

**Comment by szymanek-event-it** [comment]
Still having the same class definitions in my chunk-vendors. Do I need to import the lib differently?

**Comment by Aymkdn** [comment]
I confirm too: the problem still exists in 3.3.0

**Comment by szymanek-event-it** [comment]
Got a solution that works with the way I'm using webpack. I use Vue-Cli where I now added  
`transpileDependencies:['fast-csv']`  
To my vue.config.js

This did the trick for me. The newest version of the lib now works in IE 11.

See https://cli.vuejs.org/config/#transpiledependencies

**Comment by szymanek-event-it** [comment]
Change the exclude expression in your babel config to include the fast-csv lib, if you are using babel with webpack outside of Vue-Cli. By default all node_modules get ignored by babel.

**Comment by yoyo837** [comment]
We need the library used by the browser `script` tag.

**Comment by szymanek-event-it** [comment]
@yoyo837 I assume you want to include the lib directly into the document? In this case you should use the version in the /dist/es5/ directory. guyonroche's fix should apply there and make it work.
